// Shared test fixtures for natalis test suite

export function makeCountry(overrides = {}) {
  return {
    name: 'TestLand',
    capital: 'Testville',
    currency: 'TST',
    archetype: 'wealthy_west',
    gdp: 'high',
    healthcare: 'good',
    lifeExpectancy: 78,
    conflictRisk: 0.01,
    genderGap: 0.2,
    socialMobility: 'moderate',
    regime: 'democracy',
    regimeHistory: [],
    lgbtqCriminalized: false,
    lgbtqLegalYear: null,
    casteSystem: false,
    childMarriageRisk: 0,
    urbanRate: 0.8,
    literacyMale: 0.99,
    literacyFemale: 0.98,
    wealthTierWeights: [0.1, 0.2, 0.4, 0.2, 0.1],
    namePool: { male: ['John', 'Bob', 'Tom'], female: ['Jane', 'Alice', 'Mary'] },
    surnames: ['Doe', 'Smith', 'Jones'],
    languages: ['English'],
    yearRange: [1950, 2000],
    religionWeights: { secular: 1.0 },
    ethnicGroups: [{ id: 'local', name: 'Local', share: 1.0 }],
    context: 'A generic test country.',
    ...overrides,
  }
}

export function makeCharacter(overrides = {}) {
  const country = overrides.country ?? makeCountry()
  return {
    name: 'Jane Doe',
    firstName: 'Jane',
    surname: 'Doe',
    gender: 'female',
    birthYear: 1980,
    country,
    wealthTier: 3,
    familyStability: 'stable',
    familySize: 3,
    religion: 'secular',
    ethnicity: 'local',
    ruralUrban: 'urban',
    literate: true,
    initialStats: { happiness: 70, health: 75, smarts: 60, looks: 55, charisma: 55, wealth: 50 },
    birthPlace: null,
    birthNeighborhoodTier: 'middle_class',
    birthNeighborhoodName: null,
    ...overrides,
  }
}

export function makeState(overrides = {}) {
  const character = overrides.character ?? makeCharacter()
  return {
    screen: 'life',
    character,
    religion: null,
    classTier: null,
    ethnicity: null,
    ruralUrban: null,
    literate: true,
    stats: { happiness: 70, health: 75, smarts: 60, looks: 55, charisma: 55, wealth: 50 },
    flags: [],
    regret: 0,
    age: 10,
    currentYear: 1990,
    usedEventMap: new Map(),
    queue: [],
    pendingEvent: null,
    lastOutcome: null,
    mem: {},
    log: [],
    career: null,
    education: { level: 'none', field: null, enrolled: null },
    partner: null,
    children: [],
    criminalRecord: [],
    inPrison: false,
    prisonSentence: 0,
    worldEventsFired: new Set(),
    actionsThisYear: 0,
    maxActionsPerYear: 2,
    dead: false,
    causeOfDeath: null,
    ribbon: null,
    epitaph: '',
    money: 5000,
    debt: 0,
    creditScore: 700,
    fitness: 50,
    hooksUpCount: 0,
    parents: {
      mother: { name: 'Mary Doe', alive: true, currentAge: 45, relationshipQuality: 70 },
      father: { name: 'Bob Doe', alive: true, currentAge: 48, relationshipQuality: 65 },
    },
    karma: 50,
    fame: 0,
    siblings: [],
    pets: [],
    travels: [],
    assets: { properties: [], vehicles: [] },
    licenceObtained: false,
    retired: false,
    friends: [],
    socialMedia: { followers: 0, verified: false, genre: null },
    martialArts: { discipline: null, belt: 0 },
    birthControl: false,
    gpa: null,
    mentalHealth: { condition: null, medicating: false, therapy: false },
    hobbies: {},
    pendingMinigame: null,
    business: null,
    wanted: false,
    wantedFor: null,
    assumedIdentity: null,
    exPartners: [],
    pendingPartner: null,
    currentCountry: null,
    currentPlace: null,
    currentNeighborhoodTier: null,
    currentNeighborhoodName: null,
    residencyStatus: 'citizen',
    yearsAbroad: 0,
    pendingTrial: null,
    desire: null,
    political_leaning: null,
    conditions: [],
    gold: 0,
    householdContribution: { annualAmount: 0, obligationType: null, reduced: false },
    rosca: null,
    jointFamily: false,
    jointFamilyPool: 0,
    banked: false,
    hardCurrencyReserve: 0,
    workStatus: null,
    currentProject: null,
    echoQueue: [],
    legacy: 0,
    ...overrides,
  }
}

// Create an adult state (age 25) suitable for career/crime tests
export function makeAdultState(overrides = {}) {
  return makeState({
    age: 25,
    currentYear: 2005,
    education: { level: 'secondary', field: null, enrolled: null },
    ...overrides,
  })
}
