#!/usr/bin/env node
/**
 * stats.js — the corpus counts, computed rather than typed.
 *
 * CLAUDE.md and the docs carried hand-typed counts that disagreed with each
 * other and with the code (events 8,228 / 8,025 / ~8,000 against 8,903;
 * places 393 / 389 against 463). The interface already derives its counts;
 * so do the docs now. `npm run stats` prints them and writes docs/stats.md.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { registerResolveHooks } from './lib/register.js'

registerResolveHooks()
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const { EVENTS, classifyEvent } = await import('../src/data/events.js')
const { COUNTRIES } = await import('../src/data/countries.js')
const { PLACES } = await import('../src/data/places.js')
const { WORLD_EVENTS } = await import('../src/data/worldEvents.js')
const { CAREERS } = await import('../src/data/careers.js')
const { FLAG_REGISTRY } = await import('../src/data/flags/index.js')
const ribbonsMod = await import('../src/data/ribbons.js')
const RIBBONS = ribbonsMod.RIBBONS ?? ribbonsMod.default ?? []

const evs = EVENTS.filter(Boolean)
for (const e of evs) classifyEvent(e)
const by = (f) => evs.filter(f).length
const registers = {}
for (const e of evs) registers[e.register] = (registers[e.register] ?? 0) + 1
const files = (dir) => fs.readdirSync(path.join(ROOT, dir)).filter(f => /^events_.*\.js$/.test(f)).length
const modules = ['thematic', 'lifecycle', 'geographic', 'sonder', 'specific_lives', 'followthrough', 'prison']
  .map(d => [d, files(`src/data/events/${d}`)])

const rows = [
  ['countries', COUNTRIES.length],
  ['named places', PLACES.length],
  ['character events', evs.length],
  ['  contemplative (sonder layer)', by(e => e.contemplative)],
  ['  stranger glimpses', by(e => e.isGlimpse)],
  ['  follow-through (require another event\'s flag or mem)', by(e => e.continuesFlag?.length || e.continuesMem?.length)],
  ['  dated (claim their year)', by(e => e.dated)],
  ...Object.entries(registers).sort().map(([k, v]) => [`  register: ${k}`, v]),
  ['event modules', modules.reduce((s, [, n]) => s + n, 0)],
  ...modules.map(([d, n]) => [`  ${d}/`, n]),
  ['world events', WORLD_EVENTS.length],
  ['careers', CAREERS.length],
  ['registered flags', Object.keys(FLAG_REGISTRY).length],
  ['ribbons', Array.isArray(RIBBONS) ? RIBBONS.length : Object.keys(RIBBONS).length],
]
const width = Math.max(...rows.map(r => r[0].length))
const text = rows.map(([k, v]) => `${k.padEnd(width)}  ${v.toLocaleString('en-US')}`).join('\n')
console.log(text)
if (!process.argv.includes('--print')) {
  fs.writeFileSync(path.join(ROOT, 'docs/stats.md'),
    `# Corpus counts\n\nGenerated by \`npm run stats\` (scripts/stats.js). Do not edit by hand.\n\n\`\`\`\n${text}\n\`\`\`\n`)
}
